/**
 *
 * $Id$
 */
package ecore.org.graphstream.graph.implementations.validation;

import java.util.ArrayList;
import java.util.HashMap;

/**
 * A sample validator interface for {@link ecore.org.graphstream.graph.implementations.AbstractElement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AbstractElementValidator {
	boolean validate();

	boolean validateId(String value);
	boolean validateIndex(int value);
	boolean validateAttributes(HashMap<String, Object> value);
	boolean validateAttributesBeingRemoved(ArrayList<String> value);
}
