/**
 *
 * $Id$
 */
package ecore.org.graphstream.graph.implementations.validation;

import ecore.org.graphstream.graph.implementations.AbstractGraph;
import ecore.org.graphstream.graph.implementations.AbstractNode;

/**
 * A sample validator interface for {@link ecore.org.graphstream.graph.implementations.AbstractEdge}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AbstractEdgeValidator {
	boolean validate();

	boolean validateSource(AbstractNode value);
	boolean validateTarget(AbstractNode value);
	boolean validateDirected(boolean value);
	boolean validateGraph(AbstractGraph value);
}
