/**
 *
 * $Id$
 */
package ecore.org.graphstream.graph.implementations.validation;

import ecore.org.graphstream.graph.Graph;

/**
 * A sample validator interface for {@link ecore.org.graphstream.graph.implementations.AbstractNode}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AbstractNodeValidator {
	boolean validate();

	boolean validateGraph(Graph value);
}
