/**
 *
 * $Id$
 */
package ecore.org.graphstream.graph.implementations.validation;

import org.graphstream.graph.EdgeFactory;
import org.graphstream.graph.NodeFactory;

import ecore.org.graphstream.graph.Edge;
import ecore.org.graphstream.graph.Node;

/**
 * A sample validator interface for {@link ecore.org.graphstream.graph.implementations.AbstractGraph}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AbstractGraphValidator {
	boolean validate();

	boolean validateStrictChecking(boolean value);
	boolean validateAutoCreate(boolean value);
	boolean validateNodeFactory(NodeFactory<? extends Node> value);
	boolean validateEdgeFactory(EdgeFactory<? extends Edge> value);
	boolean validateStep(double value);
	boolean validateNullAttributesAreErrors(boolean value);
	boolean validateReplayId(long value);
}
